{% set name = "holidays-ext" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/holidays-ext-{{ version }}.tar.gz
  sha256: b2f80051dc3191262b9a95a6c625427a53a50814b0f162a87fdb22fccf978090

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.15.4
    - pandas >=1.0.4
    - python-dateutil >=2.8.0
    - lunarcalendar-ext >=0.0.1
    - convertdate >=2.1.2
    - holidays >=0.9.5

test:
  imports:
    - holidays_ext
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kaixuyang/holidays-extension
  summary: Extended holidays package
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
